spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: industrial-ai-assistant


langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus
        api-key: ${DASHSCOPE_API_KEY}