spring:
  config:
    import: optional:file:.env[.properties] #加载.env文件的环境变量DASHSCOPE_API_KEY
  application:
    name: industrial-ai-assistant


langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus
        api-key: ${DASHSCOPE_API_KEY}
      embedding-model:
        model-name: text-embedding-v3
        api-key: ${DASHSCOPE_API_KEY}
bigmodel:
  api-key: ${BIGMODEL_API_KEY}