spring:
  config:
    import: optional:file:.env[.properties] # 加载.env文件的环境变量DASHSCOPE_API_KEY
  application:
    name: industrial-ai-assistant

server:
  port: 8081
  servlet:
    context-path: /api

app:
  ai:
    qwen:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${DASHSCOPE_API_KEY} # 阿里云百炼 API Key
      model-name: qwen3.5-plus

langchain4j:
  community:
    dashscope:
      embedding-model:
        model-name: text-embedding-v2
        api-key: ${DASHSCOPE_API_KEY} # 阿里云百炼 API Key

bigmodel:
  api-key: ${BIGMODEL_API_KEY} # 智谱 MCP API Key